a = int(input("A number: "))
b = int(input("B number: "))
print(f"Tong: {a+b}")
print(f"Hieu: {a-b}")
print(f"Tich: {a*b}")
print(f"Thuong: {a/b}")
print(f"Du: {a%b}")
print(f"Phan nguyen: {a/b:.0f}")
print(f"2 chu so thap phan: {a/b:.2f}")